language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo test --features=serialize
  - cargo test --features=rand
  - cargo test --all-features
  - cargo test
